[package]
name = "zed-golangci-lint"
version = "0.1.1"
edition = "2021"
publish = false
license = "MIT"

[lib]
path = "src/golangci-lint.rs"
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.0.6"
