id = "golangci-lint"
name = "Golangci-Lint"
description = "Golangci Lint support."
version = "0.1.1"
schema_version = 1
authors = ["Jordan Gregory <jordan@j4ng5y.dev>"]
repository = "https://github.com/devgkz/zed-golangci-lint"

[language_servers.golangci-lint]
name = "golangci-lint"
language = "Go"
